"""12

Revision ID: 1fd473e6f56a
Revises: fd7cf418a2af
Create Date: 2017-03-19 12:07:14.196979

"""

# revision identifiers, used by Alembic.
revision = '1fd473e6f56a'
down_revision = 'fd7cf418a2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msgs')
    ### end Alembic commands ###
