"""w

Revision ID: 467c0bc716f9
Revises: 496f8d70bb35
Create Date: 2017-03-19 20:44:33.324390

"""

# revision identifiers, used by Alembic.
revision = '467c0bc716f9'
down_revision = '496f8d70bb35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('weibos', sa.Column('avart', sa.String(), nullable=True))
    op.add_column('weibos', sa.Column('avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibos', 'avatar')
    op.drop_column('weibos', 'avart')
    op.drop_column('comments', 'avatar')
    ### end Alembic commands ###
